#!/usr/bin/env python3
"""Generate docs/v5/ACTIVITY_ROUTING_MATRIX.md (G0 artifact) from the resolver config.

Single source of truth = the structure encoded below, which mirrors
v5/activity/_util_resolveContactAction.deluge + the §0 per-path rules in the plan.
Regenerate after any resolver change:  python scripts/gen_activity_matrix.py

Architecture law: ONE commercial email chain keyed `<stage>:<step>:<kind>`.
Sequence_Type (Email/Call/Manual) only selects the activity record (Task/Call/Meeting).
A Call/Manual step sends the shared template ONLY when email_required is true.
No V5 function creates a Meeting; reps/booking integration do; handleMeetingEvent detects.
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "docs", "v5", "ACTIVITY_ROUTING_MATRIX.md")

SLUG = {
    "Marketing Consent": "marketing-consent",
    "Demo Booking": "demo-booking",
    "Demo Confirmation": "demo-confirmation",
    "Demo Hosted": "demo-hosted",
    "Proposal Preparation": "proposal-preparation",
    "Commercial Agreement": "commercial-agreement",
    "Onboarding": "onboarding",
    "Renewal": "renewal",
}
PROGRESSION = {
    "Marketing Consent": "Demo Booking",
    "Demo Booking": "Demo Confirmation",
    "Demo Confirmation": "Demo Hosted",
    "Demo Hosted": "Proposal Preparation",
    "Proposal Preparation": "Commercial Agreement",
    "Commercial Agreement": "Onboarding",
    "Onboarding": "Renewal",
    "Renewal": "Renewal",
}
CADENCE = ["Marketing Consent", "Demo Booking", "Demo Hosted", "Commercial Agreement", "Renewal"]
MEETING = ["Demo Confirmation"]
TASK = ["Proposal Preparation", "Onboarding"]
K = 5  # resolver-default step count per cadence stage (confirmed: 5x5)


def kind(n, k=K):
    return "initial" if n == 1 else ("final" if n == k else "follow-up")


def entry_rows(stage, trigger):
    """Concrete entry action for a stage, per Sequence_Type (cadence) or path-agnostic."""
    s = SLUG[stage]
    rows = []
    if stage in CADENCE:
        rows.append((stage, "1", "Email", trigger, "send_email_now (step1)", "1 scheduled-email→audit Task", "—", "—", "Yes", f"{s}:1:initial", "send → step 2"))
        rows.append((stage, "1", "Call", trigger, "create_call (step1)", "—", "Call 1", "—", "No", "—", "Call_Outcome"))
        rows.append((stage, "1", "Manual", trigger, "create_task (manual step1)", "manual rep Task 1", "—", "—", "No", "—", "Task outcome"))
    elif stage in MEETING:
        rows.append((stage, "0", "any", trigger, "await_meeting", "—", "—", "exists (rep/integration)", "Yes (first link)", f"{s}:0:confirmation", "Demo_Outcome"))
    elif stage in TASK:
        if stage == "Proposal Preparation":
            rows.append((stage, "0", "any", trigger, "create_task", "Draft Commercials (blocking)", "—", "—", "No", "—", "Task positive / Commercials_Status=Sent"))
        else:  # Onboarding
            rows.append((stage, "0", "any", trigger, "create_task", "Onboarding Setup (blocking)", "—", "—", "Yes (kickoff)", f"{s}:0:kickoff", "Task positive"))
    return rows


def md_table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def main():
    H = ["Stage", "Step", "Sequence_Type", "Trigger", "Action", "Task", "Call", "Meeting", "email_required", "Template key", "Next"]
    parts = []
    parts.append("# Activity-Routing Matrix (G0 — GENERATED; do not hand-edit)\n")
    parts.append("Generated by `scripts/gen_activity_matrix.py` from the resolver config "
                 "(5 cadence stages × 5 steps; Demo Confirmation meeting-only; Proposal "
                 "Preparation + Onboarding task-only). **One commercial email chain keyed "
                 "`<stage>:<step>:<kind>`; `Sequence_Type` only selects the Task/Call/Meeting "
                 "record; the shared template is sent only when `email_required`.**\n")

    # A. Cadence per-path stepping (5 × 5 × 3)
    aRows = []
    for stage in CADENCE:
        s = SLUG[stage]
        for n in range(1, K + 1):
            kd = kind(n)
            nxtE = "Complete (await reply)" if n == K else f"send → step {n+1}"
            aRows.append((stage, n, "Email", f"step-{n}", "send_email_now" if n == 1 else "schedule_email",
                          "1 scheduled-email→audit Task", "—", "—", "Yes", f"{s}:{n}:{kd}", nxtE))
            nxtC = "Call_Outcome → terminal follow-up" if n == K else f"Call_Outcome → step {n+1}"
            aRows.append((stage, n, "Call", f"step-{n}", "create_call",
                          "—", f"Call {n}", "—", "Yes on neutral/noanswer", f"{s}:{n}:follow-up", nxtC))
            nxtM = "terminal" if n == K else f"Task outcome → step {n+1}"
            aRows.append((stage, n, "Manual", f"step-{n}", "create_task",
                          f"manual rep Task {n}", "—", "—", "No (unless step flagged)", "— (key when flagged)", nxtM))
    parts.append("## A. Cadence per-path stepping (concrete; 5 stages × 5 steps × 3 paths)\n" + md_table(H, aRows))

    # B. Activation entry per stage
    bRows = []
    for stage in CADENCE:
        bRows += entry_rows(stage, "activate:email/call/manual")
    for stage in MEETING + TASK:
        bRows += entry_rows(stage, "activate:* (class entry)")
    bRows.append(("(any)", "—", "any", "activate:stop / Suppress", "none (Stopped)", "—", "—", "—", "No", "—", "— (only true stop)"))
    parts.append("## B. Activation entry (concrete, per stage)\n" + md_table(H, bRows))

    # C. Call outcomes per cadence stage
    cRows = []
    for stage in CADENCE:
        s = SLUG[stage]
        nxt = PROGRESSION[stage]
        # positive -> advance to next stage entry (expand per Seq_Type of the next entry)
        for er in entry_rows(nxt, f"call:positive (→{nxt})"):
            cRows.append(er)
        cRows.append((stage, "n<5", "Call", "call:neutral / call:noanswer", "send_email + create_call n+1", "—", "Call n+1", "—", "Yes", f"{s}:n:follow-up", "Call_Outcome"))
        cRows.append((stage, "5", "Call", "call:neutral / call:noanswer", "schedule terminal follow-up", "1 scheduled-email→audit", "—", "—", "Yes", f"{s}:5:final", "Complete (await reply)"))
        cRows.append((stage, "n", "Call", "call:deferred", "reschedule same call", "—", "Call (new date)", "—", "No", "—", "Call_Outcome"))
        cRows.append((stage, "n", "Call", "call:negative / call:donotcontact", "stop + loss", "—", "—", "—", "No", "—", "terminal (Deal viability)"))
        cRows.append((stage, "n", "Call", "call:manualonly", "Manual/Stopped", "—", "—", "—", "No", "—", "—"))
        cRows.append((stage, "n", "Call", "call:baddata / call:notrelevant", "resumable block", "aux Task (Data Repair / Manual Review)", "—", "—", "No", "—", "aux Task completion → resume"))
        cRows.append((stage, "n", "Call", "call:alreadyhandled", "no-op", "—", "—", "—", "No", "—", "—"))
    parts.append("## C. Call-path outcomes (concrete, per cadence stage)\n" + md_table(H, cRows))

    # D. Event / task / meeting transitions
    dRows = []
    dRows.append(("Proposal Preparation", "0", "any", "task:positive", "advance → Commercial Agreement entry", "(see B: Commercial Agreement)", "—", "—", "—", "—", "Commercial Agreement"))
    dRows.append(("Onboarding", "0", "any", "task:positive", "advance → Renewal entry", "(see B: Renewal)", "—", "—", "—", "—", "Renewal"))
    dRows.append(("Demo Hosted", "—", "any", "demo:qualified", "→ Proposal Preparation", "Draft Commercials Task", "—", "—", "Yes", "demo-hosted:0:post-demo", "Commercials_Status"))
    dRows.append(("Demo Hosted", "—", "any", "demo:followup", "→ Demo Hosted entry", "(see B/A: Demo Hosted)", "—", "—", "per step", "demo-hosted:n:*", "per outcome"))
    dRows.append(("Demo Hosted", "—", "any", "demo:not_qualified", "stop + loss", "—", "—", "—", "No", "—", "terminal"))
    dRows.append(("Demo Confirmation", "0", "any", "demo:noshow", "re-book → Demo Booking entry", "(see B: Demo Booking)", "—", "—", "Yes", "demo-confirmation:0:no-show", "per outcome"))
    dRows.append(("Demo Confirmation", "0", "any", "demo:cancelled", "→ Demo Booking entry", "(see B: Demo Booking)", "—", "—", "No", "—", "per outcome"))
    dRows.append(("Demo Confirmation", "0", "any", "demo:rescheduled", "stamp Demo_Status only", "—", "—", "—", "No", "—", "Demo_Outcome"))
    dRows.append(("Commercial Agreement", "0", "any", "commercial:sent", "→ Commercial Agreement entry + terms", "(see B: Commercial Agreement)", "—", "—", "Yes", "commercial-agreement:0:proposal-sent", "signed / cadence"))
    dRows.append(("Onboarding", "0", "any", "commercial:signed", "→ Onboarding entry", "Onboarding Setup Task", "—", "—", "Yes", "onboarding:0:signed-confirmation", "Task positive"))
    dRows.append(("Commercial Agreement", "0", "any", "commercial:rejected", "stop + loss", "—", "—", "—", "No", "—", "terminal"))
    dRows.append(("Commercial Agreement", "0", "any", "commercial:followup_due", "re-engage cadence", "(per Seq_Type, see A)", "(per Seq_Type)", "—", "Yes", "commercial-agreement:0:follow-up", "reply / signed"))
    dRows.append(("Demo Confirmation", "0", "any", "meeting:created / booked", "await_meeting", "—", "—", "exists (rep/integration)", "Yes", "demo-confirmation:0:confirmation", "Demo_Outcome"))
    dRows.append(("Demo Confirmation", "0", "any", "meeting:attended", "→ Demo Hosted entry", "(see B: Demo Hosted)", "—", "—", "No", "—", "per outcome"))
    dRows.append(("Demo Confirmation", "0", "any", "meeting:cancelled", "→ Demo Booking entry", "(see B: Demo Booking)", "—", "—", "No", "—", "per outcome"))
    dRows.append(("Demo Confirmation", "0", "any", "meeting:noshow", "recover → Demo Booking entry", "(see B: Demo Booking)", "—", "—", "Yes", "demo-confirmation:0:no-show", "per outcome"))
    for stage in CADENCE:
        dRows.append((stage, "5", "Email", "email:postcall_due", "send terminal follow-up", "wake-up Task → audit", "—", "—", "Yes", f"{SLUG[stage]}:5:final", "Complete"))
    dRows.append(("(any)", "current", "any", "resume", "re-materialise current outstanding step (per A)", "(per Seq_Type)", "(per Seq_Type)", "—", "per step", "(per step)", "guarded by open blocking Task"))
    parts.append("## D. Event / task / meeting / scheduled transitions (concrete)\n" + md_table(H, dRows))

    parts.append("\n### Meeting ownership\nNo V5 function creates a Meeting/Event. Demos are "
                 "created by the rep (manual booking) or a booking integration; `handleMeetingEvent` "
                 "(WF007) detects/processes the existing Event; `await_meeting` waits; `sendDemoReminder` "
                 "(WF010c) only sends the reminder.\n")
    parts.append("\n### email_required summary\n- Email path: every cadence step (the email IS the step).\n"
                 "- Call path: only on `call:neutral`/`call:noanswer` (the accompanying follow-up).\n"
                 "- Manual path: only when a step is explicitly flagged `email_required` (default none).\n"
                 "- Event singletons (`:0:*`) send their template regardless of `Sequence_Type`.\n")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n\n".join(parts) + "\n")
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
